apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-app
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/Ghanathey-Neelesh-Kumar/gitops-demo.git
    targetRevision: HEAD
    path: redis-app/k8s
  
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-app
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
