apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: redis-app
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30379    # optional fixed NodePort (must be between 30000–32767)
  type: NodePort
